Sub filterKeywords()
    
    Dim keyphrase As String
    Dim hot_keywords() As Variant
    Dim hotKeyLength As Integer
    hotKeywords = Array("course", "diploma", "certificate", "certification", "school", "learn", "bach", "master", "degree", "graduate", "training", "class", "bootcamp", "boot camp", "institute", "college", "university", "universities", "fundamental", "intro", "mba", "study", "education", "become a", "curriculum")

    ' Add a sheet named "Filtered Keywords"
    Sheets.Add.Name = "Filtered_Keywords"
    'move to be last sheet
    Sheets("Filtered_Keywords").Move after:=Worksheets(Worksheets.Count)
    ' Specify the location of the combined sheet
    Set filtered_keywords = Worksheets("Filtered_Keywords")
    
    ' Add a sheet named "Eliminated Keywords"
    Sheets.Add.Name = "Eliminated_Keywords"
    ' Move sheet to be last sheet
    Sheets("Eliminated_Keywords").Move after:=Worksheets(Worksheets.Count)
    ' Specify the location of the combined sheet
    Set eliminated_keywords = Worksheets("Eliminated_Keywords")
    
    'find number of rows of sheet with keywords generated by UI
    lastRow = Sheets(1).Cells(Rows.Count, "B").End(xlUp).Row
   
    'Row indicator for filtered keywords
    phrase_count = 1 
    'row indicator for eliminated keywords
    elim_count = 1

    'loop through each keyword from UI generated list
    For i = 2 To lastRow

        'set variable to keyword
        phrase = Sheets(1).Range("B" & i).Value
        'add flag for hit on keyword
        keyword_flag = 0 

        'loop through each word in recommended word list
        For Each element in hotKeywords
            'if the word in in the keyword, put keyword in filtered list
            If InStr(1, phrase, element) <> 0 Then
                filtered_keywords.Range("A" & phrase_count).Value = phrase
                'increase count for proper placement of next keyword
                phrase_count = phrase_count + 1
                'set flag to 1 to indicate this keyword has been placed in filtered list
                keyword_flag = 1
                'stop checking for other words from that keyword and move to the next one
                Exit For 
            End If
        Next element
        'if keyword didn;t fit any of the words in the list, put in eliminated keywords sheet
        If keyword_flag = 0 Then
            eliminated_keywords.Range("A" & elim_count).Value = phrase
            elim_count = elim_count + 1
        End If
    Next i

'check for correct number of records
' MsgBox(phrase_count - 1)
' MsgBox(elim_count -1 )
' MsgBox(phrase_count + elim_count - 2)

End Sub


